// Public deployment configuration only. Never place a service-role key here.
// Generated by scripts/configure-cloud.js when free infrastructure is ready.
export const CLOUD = Object.freeze({
  enabled: false,
  url: '',
  publishableKey: '',
  appVersion: '2.1.0-monitoring',
});
