/**
 * Icon / asset verification
 *
 * The icons are generated by `scripts/generate-icons.js` rather than exported
 * from a design tool, which means they can be wrong in ways nobody notices:
 * they are only ever seen at 32–192px on a home screen, and a broken one just
 * shows up as a blank tile weeks later.
 *
 * That is exactly what happened. `applyRoundedMask()` had its corner signs
 * flipped, so it punched out **100%** of every icon's pixels — every icon and
 * the favicon shipped fully transparent. Nothing caught it because a
 * transparent PNG still decodes fine and still has the right dimensions.
 *
 * So this suite decodes the actual PNG bytes and asserts on alpha coverage,
 * corner rounding, the palette, and that the maskable variants are full-bleed
 * (Android crops maskable icons to a circle, so transparent edges would show
 * as a dark ring).
 *
 * Run: node scripts/test-assets.js
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

let pass = 0;
let fail = 0;

function assert(name, actual, expected) {
  const ok = Object.is(actual, expected);
  if (ok) { pass++; console.log(`  \u2713 ${name}`); }
  else { fail++; console.log(`  \u2717 ${name} \u2014 expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`); }
}

function assertTrue(name, cond, detail = '') {
  if (cond) { pass++; console.log(`  \u2713 ${name}`); }
  else { fail++; console.log(`  \u2717 ${name}${detail ? ' \u2014 ' + detail : ''}`); }
}

/* ==========================================================================
   Minimal PNG decoder (RGBA / RGB, 8-bit, all five filter types)
   ========================================================================== */

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

function decodePNG(buffer) {
  if (!buffer.subarray(0, 8).equals(PNG_SIGNATURE)) throw new Error('not a PNG');

  let pos = 8;
  let width = 0;
  let height = 0;
  let bitDepth = 0;
  let colorType = 0;
  const idat = [];

  while (pos < buffer.length) {
    const length = buffer.readUInt32BE(pos);
    const type = buffer.toString('ascii', pos + 4, pos + 8);
    const data = buffer.subarray(pos + 8, pos + 8 + length);
    if (type === 'IHDR') {
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      bitDepth = data[8];
      colorType = data[9];
    } else if (type === 'IDAT') {
      idat.push(data);
    } else if (type === 'IEND') {
      break;
    }
    pos += 12 + length;
  }

  if (bitDepth !== 8) throw new Error(`unsupported bit depth ${bitDepth}`);
  const channels = colorType === 6 ? 4 : colorType === 2 ? 3 : 0;
  if (!channels) throw new Error(`unsupported colour type ${colorType}`);

  const raw = zlib.inflateSync(Buffer.concat(idat));
  const stride = width * channels;
  const pixels = Buffer.alloc(width * height * channels);

  // Undo the per-scanline filters (PNG spec §9.2).
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)];
    const src = raw.subarray(y * (stride + 1) + 1, y * (stride + 1) + 1 + stride);
    const out = pixels.subarray(y * stride, (y + 1) * stride);
    const prev = y === 0 ? null : pixels.subarray((y - 1) * stride, y * stride);

    for (let i = 0; i < stride; i++) {
      const a = i >= channels ? out[i - channels] : 0;
      const b = prev ? prev[i] : 0;
      const c = prev && i >= channels ? prev[i - channels] : 0;
      let v = src[i];
      if (filter === 1) v += a;
      else if (filter === 2) v += b;
      else if (filter === 3) v += (a + b) >> 1;
      else if (filter === 4) {
        const p = a + b - c;
        const pa = Math.abs(p - a);
        const pb = Math.abs(p - b);
        const pc = Math.abs(p - c);
        v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
      } else if (filter !== 0) {
        throw new Error(`unknown filter ${filter} on row ${y}`);
      }
      out[i] = v & 0xff;
    }
  }

  return {
    width,
    height,
    channels,
    /** [r, g, b, a] — alpha defaults to 255 for RGB images. */
    at(x, y) {
      const i = (y * width + x) * channels;
      return [pixels[i], pixels[i + 1], pixels[i + 2], channels === 4 ? pixels[i + 3] : 255];
    },
    alphaStats() {
      let transparent = 0;
      let opaque = 0;
      for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
          if (this.at(x, y)[3] === 0) transparent++;
          else opaque++;
        }
      }
      return { transparent, opaque, total: width * height, transparentRatio: transparent / (width * height) };
    },
    distinctColors() {
      const seen = new Set();
      for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
          const [r, g, b, a] = this.at(x, y);
          if (a === 0) continue;
          seen.add(`${r},${g},${b}`);
        }
      }
      return seen;
    },
  };
}

const HEX = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
const GREEN = HEX('#2E7D32');
const GREEN_DARK = HEX('#1B5E20');
const GOLD = HEX('#F9A825');
const CREAM = HEX('#FFF8E1');

const same = (px, rgb, tolerance = 12) =>
  Math.abs(px[0] - rgb[0]) <= tolerance && Math.abs(px[1] - rgb[1]) <= tolerance && Math.abs(px[2] - rgb[2]) <= tolerance;

const load = (rel) => {
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) return null;
  return { bytes: fs.readFileSync(abs), img: decodePNG(fs.readFileSync(abs)) };
};

/* ==========================================================================
   1. Files exist and decode
   ========================================================================== */

const ROUNDED = [
  ['assets/icons/icon-192.png', 192],
  ['assets/icons/icon-512.png', 512],
  ['assets/icons/favicon-32.png', 32],
  ['assets/icons/apple-touch-icon.png', 180],
];
const MASKABLE = [
  ['assets/icons/icon-maskable-192.png', 192],
  ['assets/icons/icon-maskable-512.png', 512],
];
const PLAIN = [['assets/logo.png', 1024]];

console.log('== Files decode ==');
const decoded = new Map();
for (const [rel, size] of [...ROUNDED, ...MASKABLE, ...PLAIN, ['favicon.png', 32]]) {
  const loaded = load(rel);
  assertTrue(`${rel} exists`, loaded !== null);
  if (!loaded) continue;
  decoded.set(rel, loaded);
  assert(`${rel} is ${size}x${size}`, `${loaded.img.width}x${loaded.img.height}`, `${size}x${size}`);
  assertTrue(`${rel} has colour data`, loaded.img.distinctColors().size > 1, `${loaded.img.distinctColors().size} distinct colours`);
}

/* ==========================================================================
   2. Alpha coverage — the regression that shipped invisible icons
   ========================================================================== */

console.log('\n== Alpha coverage (guards the transparent-icon regression) ==');
for (const [rel] of [...ROUNDED, ...PLAIN]) {
  const { img } = decoded.get(rel);
  const stats = img.alphaStats();
  // The bug this guards: the mask used to cut 100% of pixels. Anything near
  // that is a hard failure, whatever the size.
  assertTrue(`${rel} is not the transparent-icon regression`, stats.transparentRatio < 0.5, `${(stats.transparentRatio * 100).toFixed(1)}% transparent`);
  // A rounded mask removes a fixed fraction of the area at a fixed radius, but
  // pixel-centre rounding makes small icons lose proportionally more — a 32px
  // favicon gives up ~6%, a 512px icon ~1%. Hence the loose bound.
  assertTrue(`${rel} is mostly opaque`, stats.opaque / stats.total > 0.85, `${((stats.opaque / stats.total) * 100).toFixed(1)}% opaque`);
  assert(`${rel} centre pixel is opaque`, img.at(Math.floor(img.width / 2), Math.floor(img.height / 2))[3], 255);
}

console.log('\n== Maskable icons are full-bleed ==');
for (const [rel] of MASKABLE) {
  const { img } = decoded.get(rel);
  const stats = img.alphaStats();
  const w = img.width;
  // Android crops a maskable icon to a circle; a transparent corner would be
  // composited against the launcher background as a visible dark ring.
  assert(`${rel} has no transparent pixels at all`, stats.transparent, 0);
  // Background must reach every edge. The mark sits in the middle, so the four
  // corners and four edge midpoints are all background green — either the base
  // green or the darker bottom strip, both of which count as "reached".
  const edgePoints = [
    ['top-left', 0, 0], ['top-right', w - 1, 0], ['bottom-left', 0, w - 1], ['bottom-right', w - 1, w - 1],
    ['top-mid', Math.floor(w / 2), 0], ['bottom-mid', Math.floor(w / 2), w - 1],
    ['left-mid', 0, Math.floor(w / 2)], ['right-mid', w - 1, Math.floor(w / 2)],
  ];
  const notGreen = edgePoints.filter(([, x, y]) => {
    const px = img.at(x, y);
    return !same(px, GREEN) && !same(px, GREEN_DARK);
  });
  assertTrue(
    `${rel} background reaches every edge`,
    notGreen.length === 0,
    notGreen.map(([label, x, y]) => `${label}=${img.at(x, y)}`).join(' '),
  );
}

/* ==========================================================================
   3. Corner rounding
   ========================================================================== */

console.log('\n== Rounded corners ==');
for (const [rel] of ROUNDED) {
  const { img } = decoded.get(rel);
  const w = img.width;
  const h = img.height;
  const corners = [[0, 0], [w - 1, 0], [0, h - 1], [w - 1, h - 1]];
  const opaqueCorners = corners.filter(([x, y]) => img.at(x, y)[3] !== 0);
  assert(`${rel} cuts all four corners`, opaqueCorners.length, 0);
  // The mask must not eat the middle of the tile either.
  assertTrue(`${rel} keeps the mid-edge opaque`, img.at(Math.floor(w / 2), 0)[3] === 255 && img.at(0, Math.floor(h / 2))[3] === 255);
}

console.log('\n== The logo keeps its cream frame ==');
{
  const { img } = decoded.get('assets/logo.png');
  const w = img.width;
  for (const [label, x, y] of [['top-left', 2, 2], ['top-right', w - 3, 2], ['bottom-left', 2, w - 3], ['bottom-right', w - 3, w - 3]]) {
    const px = img.at(x, y);
    assertTrue(`logo ${label} corner is opaque`, px[3] === 255, `${px}`);
  }
}

/* ==========================================================================
   4. Palette — the mark must actually use the brand colours
   ========================================================================== */

console.log('\n== Palette ==');
for (const [rel] of [...ROUNDED, ...MASKABLE]) {
  const { img } = decoded.get(rel);
  const w = img.width;
  // Background: a few px in from the corner, past the rounding radius.
  const bg = img.at(Math.floor(w * 0.5), Math.floor(w * 0.08));
  assertTrue(`${rel} background is brand green`, same(bg, GREEN), `${bg} vs ${GREEN}`);

  let gold = 0;
  let cream = 0;
  for (let y = 0; y < w; y++) {
    for (let x = 0; x < w; x++) {
      const px = img.at(x, y);
      if (same(px, GOLD)) gold++;
      else if (same(px, CREAM)) cream++;
    }
  }
  assertTrue(`${rel} contains gold (${gold} px)`, gold > w * w * 0.005, `${gold} of ${w * w}`);
  assertTrue(`${rel} contains the sheet in cream (${cream} px)`, cream > w * w * 0.05, `${cream} of ${w * w}`);
}

/* ==========================================================================
   5. The root favicon is the same file the manifest-era pages reference
   ========================================================================== */

console.log('\n== Root favicon ==');
{
  const root = decoded.get('favicon.png');
  const ico = decoded.get('assets/icons/favicon-32.png');
  assertTrue('favicon.png matches assets/icons/favicon-32.png byte for byte', root.bytes.equals(ico.bytes));
  const stats = root.img.alphaStats();
  assertTrue('favicon has visible pixels', stats.opaque > 0, `${stats.opaque} opaque`);
}

/* ==========================================================================
   6. The generator itself is runnable
   ========================================================================== */

console.log('\n== Generator wiring ==');
{
  const src = fs.readFileSync(path.join(ROOT, 'scripts', 'generate-icons.js'), 'utf8');
  // package.json sets "type": "module", so a CommonJS `require` here would
  // throw at run time. This script was broken that way for a while.
  assertTrue('generator does not use require()', !/\brequire\s*\(/.test(src));
  assertTrue('generator imports zlib', /from 'node:zlib'/.test(src));
  assertTrue('generator derives __dirname for ESM', /fileURLToPath\(import\.meta\.url\)/.test(src));

  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  assertTrue('package.json exposes an icons script', typeof pkg.scripts?.icons === 'string', pkg.scripts?.icons);
}

/* ==========================================================================
   Result
   ========================================================================== */

console.log(`\n${'-'.repeat(52)}`);
console.log(`  ${pass} passed, ${fail} failed`);
console.log(`${'-'.repeat(52)}\n`);
process.exit(fail ? 1 : 0);
